# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1comp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import image_file

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 535)
        MainWindow.setMinimumSize(QtCore.QSize(417, 535))
        MainWindow.setMaximumSize(QtCore.QSize(417, 535))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 470, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Calisto MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 180, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.click)
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(220, 70, 113, 31))
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(220, 120, 113, 31))
        self.lineEdit2.setObjectName("lineEdit2")
        self.tb = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb.setGeometry(QtCore.QRect(10, 280, 401, 192))
        self.tb.setObjectName("tb")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 9, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setWindowIcon(QtGui.QIcon(':/VDlogo.png'))


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VD"))
        self.label.setText(_translate("MainWindow", "SMALLER NUMBER:"))
        self.label_2.setText(_translate("MainWindow", "GREATER NUMBER:"))
        self.label_3.setText(_translate("MainWindow", " DEVELOPED BY VIPUL"))
        self.pushButton.setText(_translate("MainWindow", "SUBTRACTION USING (1CT)"))
        self.label_4.setText(_translate("MainWindow", "WELCOME 👀"))

    def click(self):
        a = int(self.lineEdit1.text())
        b = int(self.lineEdit2.text())
        c = bin(a).replace('0b', '')
        d = bin(b).replace('0b', '')
        x = d[::-1]
        while len(x) < 8:
            x = x + '0'
        d = x[::-1]
        e = ''.join('1' if x == '0' else '0' for x in d)
        y = c[::-1]
        while len(y) < 8:
            y = y + '0'
        c = y[::-1]
        f = a - b
        g = bin(f).replace('0b', '%temp%').replace('0b', '').replace('%temp%', '')
        h = g.replace('-', '')
        z = h[::-1]
        while len(z) < 8:
            z = z + '0'
        h = z[::-1]
        i = h.replace('0', '%temp%').replace('1', '0').replace('%temp%', '1')
        self.tb.setText( "1CT("+ str(d)+ ")="+ str(e)+ "\n"+ str(c)+"+"+ str(e)+ "="+ str(i) + "\n"+ "1CT("+ str(i)+ ")"+ "="+ str(h)+ "\n"+"Answer is  "+ str(f))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
